notepad/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from notes.views import note_list_view,finish_item,delete_item,recover_item

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', note_list_view,name='note-list'),
    path('finish-item/<id>/', finish_item,name='finish-note-item'),
    path('recover-item/<id>/', recover_item,name='recover-note-item'),
    path('delete-item/<id>/', delete_item,name='delete-note-item')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

notes/models.py
from django.db import models
from django.shortcuts import reverse,redirect
# Create your models here.

LABEL_CHOICES = (
    ('P', 'primary'),
    ('SE', 'secondary'),
    ('S', 'success'),
    ('DA', 'danger'),
    ('W', 'warning'),
    ('I', 'info'),
    ('L', 'light'),
    ('D', 'dark')
)


class Note(models.Model):
    title = models.CharField(max_length=100)
    due_date = models.DateTimeField()
    label = models.CharField(choices=LABEL_CHOICES, max_length=2)
    finished = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_finish_item_url(self):
        return reverse("finish-note-item",kwargs={
            'id':self.id
        })
    def get_recover_item_url(self):
        return reverse("recover-note-item",kwargs={
            'id':self.id
        })
    def get_delete_item_url(self):
        return reverse("delete-note-item",kwargs={
            'id':self.id
        })

notes/forms.py
from django import forms
from .models import Note


class NoteModelForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'due_date', 'label']

notes/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .forms import NoteModelForm

from .models import Note
# Create your views here.


def note_list_view(request):
    form=NoteModelForm()
    if request.method=="POST":
        form=NoteModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('note-list')

    to_do_list = Note.objects.filter(finished=False)
    finished_list=Note.objects.filter(finished=True)
    context = {
        'to_do_list': to_do_list,
        'finished_list':finished_list,
        'form':form
    }
    return render(request, "note_list.html", context)

def finish_item(request,id):
    note=get_object_or_404(Note,id=id)
    note.finished=True
    note.save()
    return redirect('note-list')

def recover_item(request,id):
    note=get_object_or_404(Note,id=id)
    note.finished=False
    note.save()
    return redirect('note-list')

def delete_item(request,id):
    note=get_object_or_404(Note,id=id)
    note.delete()
    return redirect('note-list')

templates/base.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">
    <title>Base</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sticky-footer-navbar/">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.css">

<meta name="theme-color" content="#7952b3">


    
    <!-- Custom styles for this template -->
  </head>
  <body class="d-flex flex-column h-100">
    
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">-mAckRoV</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">TO-DO App</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>

<!-- Begin page content -->
<main class="flex-shrink-0">
  <div class="container">
    {% block content%}


    {% endblock %}
  </div>
</main>

<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted"></span>
  </div>
</footer>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

      
  </body>
</html>

templates/note_list.html
{% extends "base.html" %}

{% block content%}
<div class="row">
    <div class="text-center">
        <h1 class="mt-3">To-Do list
            <a  data-bs-toggle="collapse" href="#collapseExample" role="button">
                <i class="fas fa-plus fa-sm text-warning" ></i>
            </a>
        </h1>
        <hr>
    </div>

    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            <!-- {% comment %} form {% endcomment %} -->
            <form method="POST">
                {% csrf_token %}
                <div class="form-group m-3">
                    <label class=" " for="id_title">Title</label>
                    {{form.title}}
                </div>
                <div class="form-group m-3">
                    <label class=" " for="id_due_date">Due Date</label>
                    {{form.due_date}}
                </div>
                <div class="form-group m-3">
                    <label class=" " for="id_title">Label</label>
                    {{form.label}}
                </div>
                <button type="submit" class="btn btn-primary ms-3 mb-2">Submit</button>
            </form>
            <!-- {% comment %} endform {% endcomment %} -->
        </div>
    </div>


    <div class="border rounded-3 col p-2 text-center centered-form center-block position-relative ">
        <h3>Remaining</h3>
        {% for note in to_do_list %}
        <div class="card container col-md-10 col-md-offset-1" style="width: 18rem;">
            {% include "note_snippet.html" with note_snippet_var=note type="DELETE" %}
        </div>
        {% endfor %}
    </div>

    <div class="border rounded-3 col p-2 text-center centered-form center-block position-relative ">
        <h3>finished</h3>
        {% for note in finished_list %}
        <div class="card container col-md-10 col-md-offset-1" style="width: 18rem;">
            {% include "note_snippet.html" with note_snippet_var=note type="ADD" %}
        </div>
        {% endfor %}
    </div>
</div>


{% endblock content %}

templates/note_snippet.html
<div class="card-body">
    <h5 class="card-title text-capitalize">{{note_snippet_var.title}}</h5>
    <h6 class="card-subtitle mb-2 text-muted">
        <span class="badge bg-{{note.get_label_display }}">
            {{note_snippet_var.due_date}}
        </span>
    </h6>
    <p class="card-text">-mAckRoV</p>
        {% if type == "DELETE" %}
            <a href="{{note_snippet_var.get_finish_item_url}}" class="card-link text-success"><i class="fas fa-check"></i></a>
        {% else %}
            <a href="{{note_snippet_var.get_recover_item_url}}" class="card-link text-warning"><i class="fas fa-times"></i></a>
        {% endif %}
        
    <a href="{{note_snippet_var.get_delete_item_url}}" class="card-link text-danger"><i class="fas fa-dumpster"></i></a>
</div>